server:
  port: 8082

spring:
  application:
    name: service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/services
    username: service
    password: 30122003
  rabbitmq:
    addresses: amqps://ekwvjomf:s-sKR3MLT-nO2IoiGseI50e6jCkdvDKJ@jackal.rmq.cloudamqp.com/ekwvjomf
  main:
    allow-circular-references: true

eureka:
  instance:
    appname: service
  client:
    registry-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8084/eureka

broker:
  queue:
    service:
      name: default.service
      payment: product.payment
    payment:
      name: default.payment
    discord:
      request: payment.request
      response: payment.response
    auth:
      discord: auth.discord
      service: auth.service
      payment: auth.payment
      result: auth.result