server:
  port: 8080
  address: 192.168.1.106

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: authentication
          uri: lb://authentication
          predicates:
            - Path=/auth/**
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
                - DELETE
              allowedHeaders: '*'
              maxAge: 30
          filters:
            - name: AuthorizationFilter
        - id: service
          uri: lb://service
          predicates:
            - Path=/service/**
          filters:
            - name: AuthorizationFilter
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
                - DELETE
              allowedHeaders: '*'
              maxAge: 30
  main:
    allow-circular-references: true

eureka:
  instance:
    appname: gateway
  client:
    registry-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8084/eureka