server:
  port: 8081

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/payments
    username: payment
    password: 30122003
  rabbitmq:
    addresses: amqps://ekwvjomf:s-sKR3MLT-nO2IoiGseI50e6jCkdvDKJ@jackal.rmq.cloudamqp.com/ekwvjomf
  main:
    allow-circular-references: true

broker:
  queue:
    payment:
      name: default.payment
    service:
      name: default.service
    auth:
      payment: auth.payment
      result: auth.result